### Final Project - Predictor Selection via LASSO

setwd('Desktop/School/Spring 2016/Stat 154/Final Project/')

### Load R dataset
load('Data/TrainTest.RData')

Xtrain <- as.matrix(X)
ytrain <- as.numeric(y)

### Try to identify best predictors using LASSO
library(glmnet)
sample.obs <- sample(1:50000,1500)
Xtrain.scale <- scale(Xtrain)

lasso_model <- cv.glmnet(Xtrain.scale[sample.obs,], y[sample.obs], family='binomial')

plot(lasso_model)
plot(lasso_model$glmnet.fit)


### Code reused from HW3, identify indices of relevent predictors generated by LASSO

coef(lasso_model, s='lambda.1se')
lasso_model$lambda.1se
sum(coef(lasso_model, s='lambda.1se')!=0)
sum(coef(lasso_model, s=.023)!=0)


ind.nzero <- which(coef(lasso_model, s='lambda.1se')!=0)-1
ind.nzero100 <- which(coef(lasso_model, s=.024)!=0)-1

nzero.coef<- coef(lasso_model, s='lambda.1se')[ind.nzero+1][-1]
nzero.coef100 <- coef(lasso_model, s=.023)[ind.nzero100+1][-1]

words <- 1:1000
nzero.names <- (words[ind.nzero])
nzero.names100 <- (words[ind.nzero100])

as.numeric(words %in% nzero.names)

nzero.data <- data.frame(nzero.names, nzero.coef/sum(nzero.coef)*100)
nzero.data100 <- data.frame(nzero.names100, nzero.coef100/sum(nzero.coef100)*100)
nzero.data ; nzero.data100


### Build function -
### Try to repeat multiple times and store result with count vector with
### each entry equal to the number of times i is non-zero in LASSO

lasso_count <- function(x, y) {
  sample.case <- sample(1:50000, 1000) 
  model <- cv.glmnet(x[sample.case,], y[sample.case], family='binomial')
  
  ind.nzero_sim <- which(coef(model, s='lambda.1se')!=0)-1
  word <- 1:1000
  nzero.word <- (word[ind.nzero_sim])
  single_count <- as.numeric(word %in% nzero.word)
  
  return(single_count)
}

experiment_fun <- lasso_count(Xtrain.scale,y = ytrain)
experiment_fun

### Build Simulation
### Simulation function returns total count of non-zero coordinates
### for n different samples of 1000 observations. Similar to bootstrap.


lasso_sim <- function(n, x, y) {
  count <- vector(mode='numeric', length=1000)
  for(i in 1:n) {
    single_count <- lasso_count(x, y)
    count <- single_count + count
  }
  return(count)
}

experiment_sim <- lasso_sim(100, Xtrain.scale, ytrain)
experiment_sim


### Store results due to long run time
write.csv(as.matrix(experiment_sim), file='simulation_results2.csv', row.names=F)

test <- read.csv(file = 'simulation_results.csv')
test1 <- as.vector(test[,2])




results.dataFrame <- as.data.frame(test)
colnames(results.dataFrame) <- c('Word', 'Number_NonZero')
rownames(results.dataFrame) <- NULL
View(results.dataFrame)

results.sorted <- results.dataFrame[order(results.dataFrame$Number_NonZero, decreasing=T),]
rownames(results.sorted) <- NULL
View(results.sorted)


### Write sorted data to csv

write.csv(results.sorted, file='LASSO_resultSorted.csv', row.names=F)

check <- read.csv('LASSO_resultSorted.csv')
View(check)








